version: '3.8'

services:
  profile-store:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
      - "50051:50051"
    environment:
      - POSTGRES_DSN=user=postgres password=postgres host=postgres port=5432 dbname=apim sslmode=disable
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=P@ssw0rd
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_started
    networks:
      - apim-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apim-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/P@ssw0rd
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - apim-network

networks:
  apim-network:
    driver: bridge

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: