// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/api.proto

package apiv1

import (
	_ "github.com/bufbuild/buf-tour/gen/buf/validate"
	_ "github.com/bufbuild/buf-tour/gen/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ApplicationProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Graph         *ProfileGraph          `protobuf:"bytes,5,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationProfile) Reset() {
	*x = ApplicationProfile{}
	mi := &file_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationProfile) ProtoMessage() {}

func (x *ApplicationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationProfile.ProtoReflect.Descriptor instead.
func (*ApplicationProfile) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationProfile) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationProfile) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ApplicationProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApplicationProfile) GetGraph() *ProfileGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type ProfileGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileGraph) Reset() {
	*x = ProfileGraph{}
	mi := &file_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGraph) ProtoMessage() {}

func (x *ProfileGraph) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGraph.ProtoReflect.Descriptor instead.
func (*ProfileGraph) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileGraph) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CreateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *Application           `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *Application           `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *Application           `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type DeleteApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{10}
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{11}
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

type AddProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Graph         *ProfileGraph          `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProfileRequest) Reset() {
	*x = AddProfileRequest{}
	mi := &file_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileRequest) ProtoMessage() {}

func (x *AddProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileRequest.ProtoReflect.Descriptor instead.
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *AddProfileRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AddProfileRequest) GetGraph() *ProfileGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type AddProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ApplicationProfile    `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProfileResponse) Reset() {
	*x = AddProfileResponse{}
	mi := &file_v1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileResponse) ProtoMessage() {}

func (x *AddProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileResponse.ProtoReflect.Descriptor instead.
func (*AddProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *AddProfileResponse) GetProfile() *ApplicationProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_v1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProfileByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ApplicationProfile    `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDResponse) Reset() {
	*x = GetProfileByIDResponse{}
	mi := &file_v1_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDResponse) ProtoMessage() {}

func (x *GetProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetProfileByIDResponse) GetProfile() *ApplicationProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetLatestProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestProfileRequest) Reset() {
	*x = GetLatestProfileRequest{}
	mi := &file_v1_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestProfileRequest) ProtoMessage() {}

func (x *GetLatestProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestProfileRequest.ProtoReflect.Descriptor instead.
func (*GetLatestProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{17}
}

func (x *GetLatestProfileRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type GetLatestProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ApplicationProfile    `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestProfileResponse) Reset() {
	*x = GetLatestProfileResponse{}
	mi := &file_v1_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestProfileResponse) ProtoMessage() {}

func (x *GetLatestProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestProfileResponse.ProtoReflect.Descriptor instead.
func (*GetLatestProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetLatestProfileResponse) GetProfile() *ApplicationProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileByVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByVersionRequest) Reset() {
	*x = GetProfileByVersionRequest{}
	mi := &file_v1_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByVersionRequest) ProtoMessage() {}

func (x *GetProfileByVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByVersionRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByVersionRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetProfileByVersionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *GetProfileByVersionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetProfileByVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ApplicationProfile    `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByVersionResponse) Reset() {
	*x = GetProfileByVersionResponse{}
	mi := &file_v1_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByVersionResponse) ProtoMessage() {}

func (x *GetProfileByVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByVersionResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByVersionResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{20}
}

func (x *GetProfileByVersionResponse) GetProfile() *ApplicationProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_v1_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_v1_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{22}
}

type ListProfilesByApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesByApplicationRequest) Reset() {
	*x = ListProfilesByApplicationRequest{}
	mi := &file_v1_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesByApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesByApplicationRequest) ProtoMessage() {}

func (x *ListProfilesByApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesByApplicationRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesByApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{23}
}

func (x *ListProfilesByApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListProfilesByApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ApplicationProfile  `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesByApplicationResponse) Reset() {
	*x = ListProfilesByApplicationResponse{}
	mi := &file_v1_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesByApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesByApplicationResponse) ProtoMessage() {}

func (x *ListProfilesByApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesByApplicationResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesByApplicationResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{24}
}

func (x *ListProfilesByApplicationResponse) GetProfiles() []*ApplicationProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type ListLatestProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestProfilesRequest) Reset() {
	*x = ListLatestProfilesRequest{}
	mi := &file_v1_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestProfilesRequest) ProtoMessage() {}

func (x *ListLatestProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListLatestProfilesRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{25}
}

type ListLatestProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ApplicationProfile  `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestProfilesResponse) Reset() {
	*x = ListLatestProfilesResponse{}
	mi := &file_v1_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestProfilesResponse) ProtoMessage() {}

func (x *ListLatestProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListLatestProfilesResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{26}
}

func (x *ListLatestProfilesResponse) GetProfiles() []*ApplicationProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\"l\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcc\x01\n" +
	"\x12ApplicationProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x05graph\x18\x05 \x01(\v2\x14.api.v1.ProfileGraphR\x05graph\"\"\n" +
	"\fProfileGraph\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\":\n" +
	"\x18CreateApplicationRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\"R\n" +
	"\x19CreateApplicationResponse\x125\n" +
	"\vapplication\x18\x01 \x01(\v2\x13.api.v1.ApplicationR\vapplication\"4\n" +
	"\x15GetApplicationRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"O\n" +
	"\x16GetApplicationResponse\x125\n" +
	"\vapplication\x18\x01 \x01(\v2\x13.api.v1.ApplicationR\vapplication\"W\n" +
	"\x18UpdateApplicationRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x04name\"R\n" +
	"\x19UpdateApplicationResponse\x125\n" +
	"\vapplication\x18\x01 \x01(\v2\x13.api.v1.ApplicationR\vapplication\"7\n" +
	"\x18DeleteApplicationRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"\x1b\n" +
	"\x19DeleteApplicationResponse\"\x19\n" +
	"\x17ListApplicationsRequest\"S\n" +
	"\x18ListApplicationsResponse\x127\n" +
	"\fapplications\x18\x01 \x03(\v2\x13.api.v1.ApplicationR\fapplications\"s\n" +
	"\x11AddProfileRequest\x122\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\rapplicationId\x12*\n" +
	"\x05graph\x18\x02 \x01(\v2\x14.api.v1.ProfileGraphR\x05graph\"J\n" +
	"\x12AddProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.api.v1.ApplicationProfileR\aprofile\"4\n" +
	"\x15GetProfileByIDRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"N\n" +
	"\x16GetProfileByIDResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.api.v1.ApplicationProfileR\aprofile\"M\n" +
	"\x17GetLatestProfileRequest\x122\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\rapplicationId\"P\n" +
	"\x18GetLatestProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.api.v1.ApplicationProfileR\aprofile\"s\n" +
	"\x1aGetProfileByVersionRequest\x122\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\rapplicationId\x12!\n" +
	"\aversion\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\aversion\"S\n" +
	"\x1bGetProfileByVersionResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.api.v1.ApplicationProfileR\aprofile\"3\n" +
	"\x14DeleteProfileRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x02id\"\x17\n" +
	"\x15DeleteProfileResponse\"V\n" +
	" ListProfilesByApplicationRequest\x122\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\rapplicationId\"[\n" +
	"!ListProfilesByApplicationResponse\x126\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1a.api.v1.ApplicationProfileR\bprofiles\"\x1b\n" +
	"\x19ListLatestProfilesRequest\"T\n" +
	"\x1aListLatestProfilesResponse\x126\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1a.api.v1.ApplicationProfileR\bprofiles2\x86\f\n" +
	"\x13ProfileStoreService\x12u\n" +
	"\x11CreateApplication\x12 .api.v1.CreateApplicationRequest\x1a!.api.v1.CreateApplicationResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/applications\x12n\n" +
	"\x0eGetApplication\x12\x1d.api.v1.GetApplicationRequest\x1a\x1e.api.v1.GetApplicationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/applications/{id}\x12z\n" +
	"\x11UpdateApplication\x12 .api.v1.UpdateApplicationRequest\x1a!.api.v1.UpdateApplicationResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/applications/{id}\x12w\n" +
	"\x11DeleteApplication\x12 .api.v1.DeleteApplicationRequest\x1a!.api.v1.DeleteApplicationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/applications/{id}\x12o\n" +
	"\x10ListApplications\x12\x1f.api.v1.ListApplicationsRequest\x1a .api.v1.ListApplicationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/applications\x12z\n" +
	"\n" +
	"AddProfile\x12\x19.api.v1.AddProfileRequest\x1a\x1a.api.v1.AddProfileResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/applications/{application_id}/profiles\x12j\n" +
	"\x0eGetProfileByID\x12\x1d.api.v1.GetProfileByIDRequest\x1a\x1e.api.v1.GetProfileByIDResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/profiles/{id}\x12\x90\x01\n" +
	"\x10GetLatestProfile\x12\x1f.api.v1.GetLatestProfileRequest\x1a .api.v1.GetLatestProfileResponse\"9\x82\xd3\xe4\x93\x023\x121/v1/applications/{application_id}/profiles/latest\x12\x9c\x01\n" +
	"\x13GetProfileByVersion\x12\".api.v1.GetProfileByVersionRequest\x1a#.api.v1.GetProfileByVersionResponse\"<\x82\xd3\xe4\x93\x026\x124/v1/applications/{application_id}/profiles/{version}\x12g\n" +
	"\rDeleteProfile\x12\x1c.api.v1.DeleteProfileRequest\x1a\x1d.api.v1.DeleteProfileResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/profiles/{id}\x12\xa4\x01\n" +
	"\x19ListProfilesByApplication\x12(.api.v1.ListProfilesByApplicationRequest\x1a).api.v1.ListProfilesByApplicationResponse\"2\x82\xd3\xe4\x93\x02,\x12*/v1/applications/{application_id}/profiles\x12x\n" +
	"\x12ListLatestProfiles\x12!.api.v1.ListLatestProfilesRequest\x1a\".api.v1.ListLatestProfilesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/profiles/latestBz\n" +
	"\n" +
	"com.api.v1B\bApiProtoP\x01Z)github.com/bufbuild/buf-tour/gen/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_v1_api_proto_rawDescOnce sync.Once
	file_v1_api_proto_rawDescData []byte
)

func file_v1_api_proto_rawDescGZIP() []byte {
	file_v1_api_proto_rawDescOnce.Do(func() {
		file_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)))
	})
	return file_v1_api_proto_rawDescData
}

var file_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_api_proto_goTypes = []any{
	(*Application)(nil),                       // 0: api.v1.Application
	(*ApplicationProfile)(nil),                // 1: api.v1.ApplicationProfile
	(*ProfileGraph)(nil),                      // 2: api.v1.ProfileGraph
	(*CreateApplicationRequest)(nil),          // 3: api.v1.CreateApplicationRequest
	(*CreateApplicationResponse)(nil),         // 4: api.v1.CreateApplicationResponse
	(*GetApplicationRequest)(nil),             // 5: api.v1.GetApplicationRequest
	(*GetApplicationResponse)(nil),            // 6: api.v1.GetApplicationResponse
	(*UpdateApplicationRequest)(nil),          // 7: api.v1.UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil),         // 8: api.v1.UpdateApplicationResponse
	(*DeleteApplicationRequest)(nil),          // 9: api.v1.DeleteApplicationRequest
	(*DeleteApplicationResponse)(nil),         // 10: api.v1.DeleteApplicationResponse
	(*ListApplicationsRequest)(nil),           // 11: api.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),          // 12: api.v1.ListApplicationsResponse
	(*AddProfileRequest)(nil),                 // 13: api.v1.AddProfileRequest
	(*AddProfileResponse)(nil),                // 14: api.v1.AddProfileResponse
	(*GetProfileByIDRequest)(nil),             // 15: api.v1.GetProfileByIDRequest
	(*GetProfileByIDResponse)(nil),            // 16: api.v1.GetProfileByIDResponse
	(*GetLatestProfileRequest)(nil),           // 17: api.v1.GetLatestProfileRequest
	(*GetLatestProfileResponse)(nil),          // 18: api.v1.GetLatestProfileResponse
	(*GetProfileByVersionRequest)(nil),        // 19: api.v1.GetProfileByVersionRequest
	(*GetProfileByVersionResponse)(nil),       // 20: api.v1.GetProfileByVersionResponse
	(*DeleteProfileRequest)(nil),              // 21: api.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),             // 22: api.v1.DeleteProfileResponse
	(*ListProfilesByApplicationRequest)(nil),  // 23: api.v1.ListProfilesByApplicationRequest
	(*ListProfilesByApplicationResponse)(nil), // 24: api.v1.ListProfilesByApplicationResponse
	(*ListLatestProfilesRequest)(nil),         // 25: api.v1.ListLatestProfilesRequest
	(*ListLatestProfilesResponse)(nil),        // 26: api.v1.ListLatestProfilesResponse
	(*timestamppb.Timestamp)(nil),             // 27: google.protobuf.Timestamp
}
var file_v1_api_proto_depIdxs = []int32{
	27, // 0: api.v1.Application.created_at:type_name -> google.protobuf.Timestamp
	27, // 1: api.v1.ApplicationProfile.created_at:type_name -> google.protobuf.Timestamp
	2,  // 2: api.v1.ApplicationProfile.graph:type_name -> api.v1.ProfileGraph
	0,  // 3: api.v1.CreateApplicationResponse.application:type_name -> api.v1.Application
	0,  // 4: api.v1.GetApplicationResponse.application:type_name -> api.v1.Application
	0,  // 5: api.v1.UpdateApplicationResponse.application:type_name -> api.v1.Application
	0,  // 6: api.v1.ListApplicationsResponse.applications:type_name -> api.v1.Application
	2,  // 7: api.v1.AddProfileRequest.graph:type_name -> api.v1.ProfileGraph
	1,  // 8: api.v1.AddProfileResponse.profile:type_name -> api.v1.ApplicationProfile
	1,  // 9: api.v1.GetProfileByIDResponse.profile:type_name -> api.v1.ApplicationProfile
	1,  // 10: api.v1.GetLatestProfileResponse.profile:type_name -> api.v1.ApplicationProfile
	1,  // 11: api.v1.GetProfileByVersionResponse.profile:type_name -> api.v1.ApplicationProfile
	1,  // 12: api.v1.ListProfilesByApplicationResponse.profiles:type_name -> api.v1.ApplicationProfile
	1,  // 13: api.v1.ListLatestProfilesResponse.profiles:type_name -> api.v1.ApplicationProfile
	3,  // 14: api.v1.ProfileStoreService.CreateApplication:input_type -> api.v1.CreateApplicationRequest
	5,  // 15: api.v1.ProfileStoreService.GetApplication:input_type -> api.v1.GetApplicationRequest
	7,  // 16: api.v1.ProfileStoreService.UpdateApplication:input_type -> api.v1.UpdateApplicationRequest
	9,  // 17: api.v1.ProfileStoreService.DeleteApplication:input_type -> api.v1.DeleteApplicationRequest
	11, // 18: api.v1.ProfileStoreService.ListApplications:input_type -> api.v1.ListApplicationsRequest
	13, // 19: api.v1.ProfileStoreService.AddProfile:input_type -> api.v1.AddProfileRequest
	15, // 20: api.v1.ProfileStoreService.GetProfileByID:input_type -> api.v1.GetProfileByIDRequest
	17, // 21: api.v1.ProfileStoreService.GetLatestProfile:input_type -> api.v1.GetLatestProfileRequest
	19, // 22: api.v1.ProfileStoreService.GetProfileByVersion:input_type -> api.v1.GetProfileByVersionRequest
	21, // 23: api.v1.ProfileStoreService.DeleteProfile:input_type -> api.v1.DeleteProfileRequest
	23, // 24: api.v1.ProfileStoreService.ListProfilesByApplication:input_type -> api.v1.ListProfilesByApplicationRequest
	25, // 25: api.v1.ProfileStoreService.ListLatestProfiles:input_type -> api.v1.ListLatestProfilesRequest
	4,  // 26: api.v1.ProfileStoreService.CreateApplication:output_type -> api.v1.CreateApplicationResponse
	6,  // 27: api.v1.ProfileStoreService.GetApplication:output_type -> api.v1.GetApplicationResponse
	8,  // 28: api.v1.ProfileStoreService.UpdateApplication:output_type -> api.v1.UpdateApplicationResponse
	10, // 29: api.v1.ProfileStoreService.DeleteApplication:output_type -> api.v1.DeleteApplicationResponse
	12, // 30: api.v1.ProfileStoreService.ListApplications:output_type -> api.v1.ListApplicationsResponse
	14, // 31: api.v1.ProfileStoreService.AddProfile:output_type -> api.v1.AddProfileResponse
	16, // 32: api.v1.ProfileStoreService.GetProfileByID:output_type -> api.v1.GetProfileByIDResponse
	18, // 33: api.v1.ProfileStoreService.GetLatestProfile:output_type -> api.v1.GetLatestProfileResponse
	20, // 34: api.v1.ProfileStoreService.GetProfileByVersion:output_type -> api.v1.GetProfileByVersionResponse
	22, // 35: api.v1.ProfileStoreService.DeleteProfile:output_type -> api.v1.DeleteProfileResponse
	24, // 36: api.v1.ProfileStoreService.ListProfilesByApplication:output_type -> api.v1.ListProfilesByApplicationResponse
	26, // 37: api.v1.ProfileStoreService.ListLatestProfiles:output_type -> api.v1.ListLatestProfilesResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
		MessageInfos:      file_v1_api_proto_msgTypes,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
